FROM node:8

# set up angular cli
RUN yarn global add @angular/cli@1.6.2

WORKDIR /app
COPY package.json /app
COPY yarn.lock /app
RUN yarn install --pure-lockfile
COPY . /app

EXPOSE 4200

# serve webserver
CMD ng serve --host 0.0.0.0 --disable-host-check --proxy-config proxy.conf.dev.json
