version: "3"
services:
 db:
    image: mongo:3.4.0
    container_name: "mongodb"
    env_file:
      - .env
    volumes:
        - ./docker-entrypoint.sh:/entrypoint.sh
    ports:
      - "27017:27017"
    command: mongod --auth
