version: "3"
services:
  nginx:
      image: nginx
      container_name: 'nginx_prod'
      depends_on:
        - frontend
        - backend
      links:
        - backend
      volumes:
        - shared:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
  frontend:
    build:
      context: ./frontend
    container_name: "frontend_prod"
    volumes:
      - shared:/app/dist
  backend:
    build:
      context: ./backend
    container_name: "backend_prod"
    env_file:
      - .env
    volumes:
      - ./backend:/app # for watching files
    ports:
      - "8081:8081"
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:3.4.0
    container_name: "mongodb_prod"
    env_file:
      - .env
    volumes:
        - ./docker-entrypoint.sh:/entrypoint.sh
    ports:
      - "27017:27017"
    command: mongod --auth
volumes:
  shared: {}
