version: "3"
services:
 backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend"
    volumes:
        - ./backend:/app # for watching files
    ports:
      - "8081:8081"
    depends_on:
      - db
    links:
      - db
 db:
    image: mongo:3.4.0
    container_name: "mongodb"
    env_file:
      - .env
    volumes:
        - ./docker-entrypoint.sh:/entrypoint.sh
    ports:
      - "27017:27017"
    command: mongod --auth
